[package]
name = "hashtable"
version = "0.0.0"
edition = "2021"
publish = false

[profile.dev.package."*"]
opt-level = 3
overflow-checks = false

[profile.test]
opt-level = 3
overflow-checks = false

[profile.release]
debug = true

[dependencies]
ahash = "0.7.6"
bumpalo = "3.10.0"
rand = { version = "0.8.5" }
